# Generated by Django 4.0.4 on 2022-05-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facilitador',
            new_name='Clase',
        ),
    ]
